if(DEFINED TOOLCHAIN_CLANG_8_)
  return()
else()
  set(TOOLCHAIN_CLANG_8_ 1)
endif()

SET (CMAKE_C_COMPILER             "/usr/bin/clang-8")
SET (CMAKE_C_FLAGS                "-Wall -std=c99")
SET (CMAKE_C_FLAGS_DEBUG          "-g")
SET (CMAKE_C_FLAGS_MINSIZEREL     "-Os -DNDEBUG")
SET (CMAKE_C_FLAGS_RELEASE        "-O3 -DNDEBUG")
SET (CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -g")

SET (CMAKE_CXX_COMPILER             "/usr/bin/clang++-8")
SET (CMAKE_CXX_FLAGS_DEBUG          "-g")
SET (CMAKE_CXX_FLAGS_MINSIZEREL     "-Os -DNDEBUG")
SET (CMAKE_CXX_FLAGS_RELEASE        "-O3 -DNDEBUG")
SET (CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g -fno-omit-frame-pointer -fno-inline-functions -fno-optimize-sibling-calls")

SET (CMAKE_AR      "/usr/bin/llvm-ar-8")
SET (CMAKE_LINKER  "/usr/bin/llvm-link-8")
SET (CMAKE_NM      "/usr/bin/llvm-nm-8")
SET (CMAKE_OBJDUMP "/usr/bin/llvm-objdump-8")
SET (CMAKE_RANLIB  "/usr/bin/llvm-ranlib-8")
